project:
    artifactId: book
    name: book
    version: 1.0.0
    description: Demo project for info endpoint

# For Spring Actuator /info endpoint
info:
    artifact: ${project.artifactId}
    name: ${project.name}
    description: ${project.description}
    version: ${project.version}

# use a HTTP port 8080
server:
  port: 8080

#HSQLDB persistence
spring:
  datasource:
    url: jdbc:hsqldb:mem:dataSource
    username: sa
    #doesn't work in new spring version
    #schema: db/create-db.sql
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    show-sql: true